
spring:
  application:
    name: pessoa
  profiles:
    active: dev
  web:
    locale: pt_BR
    locale-resolver: fixed
  jackson:
    datatype:
      datetime:
        write-dates-as-timestamps: false
    locale: pt_BR
    time-zone: America/Sao_Paulo

management:
  otlp:
    metrics:
      export:
        enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

---

salario:
  base: 1558.00
  minimo:
    referencia: 1302.00
  taxa: 1.18
  bonus: 500.00

